//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDriver.AcclaimUrlGeneratorWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AcclaimUrlGeneratorWS.AcclaimURLGeneratorSoap")]
    public interface AcclaimURLGeneratorSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateUrl", ReplyAction="*")]
        TestDriver.AcclaimUrlGeneratorWS.GenerateUrlResponse GenerateUrl(TestDriver.AcclaimUrlGeneratorWS.GenerateUrlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateUrl", Namespace="http://tempuri.org/", Order=0)]
        public TestDriver.AcclaimUrlGeneratorWS.GenerateUrlRequestBody Body;
        
        public GenerateUrlRequest() {
        }
        
        public GenerateUrlRequest(TestDriver.AcclaimUrlGeneratorWS.GenerateUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string participantId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string blowPass;
        
        public GenerateUrlRequestBody() {
        }
        
        public GenerateUrlRequestBody(string userName, string participantId, string blowPass) {
            this.userName = userName;
            this.participantId = participantId;
            this.blowPass = blowPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateUrlResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestDriver.AcclaimUrlGeneratorWS.GenerateUrlResponseBody Body;
        
        public GenerateUrlResponse() {
        }
        
        public GenerateUrlResponse(TestDriver.AcclaimUrlGeneratorWS.GenerateUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerateUrlResult;
        
        public GenerateUrlResponseBody() {
        }
        
        public GenerateUrlResponseBody(string GenerateUrlResult) {
            this.GenerateUrlResult = GenerateUrlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AcclaimURLGeneratorSoapChannel : TestDriver.AcclaimUrlGeneratorWS.AcclaimURLGeneratorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AcclaimURLGeneratorSoapClient : System.ServiceModel.ClientBase<TestDriver.AcclaimUrlGeneratorWS.AcclaimURLGeneratorSoap>, TestDriver.AcclaimUrlGeneratorWS.AcclaimURLGeneratorSoap {
        
        public AcclaimURLGeneratorSoapClient() {
        }
        
        public AcclaimURLGeneratorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AcclaimURLGeneratorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcclaimURLGeneratorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcclaimURLGeneratorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestDriver.AcclaimUrlGeneratorWS.GenerateUrlResponse TestDriver.AcclaimUrlGeneratorWS.AcclaimURLGeneratorSoap.GenerateUrl(TestDriver.AcclaimUrlGeneratorWS.GenerateUrlRequest request) {
            return base.Channel.GenerateUrl(request);
        }
        
        public string GenerateUrl(string userName, string participantId, string blowPass) {
            TestDriver.AcclaimUrlGeneratorWS.GenerateUrlRequest inValue = new TestDriver.AcclaimUrlGeneratorWS.GenerateUrlRequest();
            inValue.Body = new TestDriver.AcclaimUrlGeneratorWS.GenerateUrlRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.participantId = participantId;
            inValue.Body.blowPass = blowPass;
            TestDriver.AcclaimUrlGeneratorWS.GenerateUrlResponse retVal = ((TestDriver.AcclaimUrlGeneratorWS.AcclaimURLGeneratorSoap)(this)).GenerateUrl(inValue);
            return retVal.Body.GenerateUrlResult;
        }
    }
}
